/**
 * Prayer and devotional texts used by the extra activities (Angelus, Stations of the
 * Cross, feast days, the 99 Names, the Gayatri mantra). Like the other scripture on the
 * site, these are shown in Chinese or English only and are not machine-translated.
 */

type Pair = [string, string];

/** The Angelus — versicle / response, then a Hail Mary after each of the first three */
export const ANGELUS: { v: Pair; r: Pair; hail: boolean }[] = [
  { v: ['上主的天使向瑪利亞報喜，', 'The Angel of the Lord declared unto Mary,'], r: ['她因聖神受孕。', 'And she conceived of the Holy Spirit.'], hail: true },
  { v: ['「主的婢女在此，', '“Behold the handmaid of the Lord.'], r: ['願照你的話成就於我。」', 'Be it done unto me according to thy word.”'], hail: true },
  { v: ['聖言成了血肉，', 'And the Word was made flesh,'], r: ['居住在我們中間。', 'And dwelt among us.'], hail: true },
  { v: ['天主聖母，請為我們祈求，', 'Pray for us, O holy Mother of God,'], r: ['使我們堪當承受基督的恩許。', 'That we may be made worthy of the promises of Christ.'], hail: false },
];
export const ANGELUS_PRAYER: Pair = [
  '請眾同禱：上主，求你將你的恩寵注入我們心中，使我們這些因天使報信，已經知道你聖子降孕成人的人，藉著他的苦難和十字架，得以達到光榮的復活。因我們的主基督。亞孟。',
  'Let us pray: Pour forth, we beseech thee, O Lord, thy grace into our hearts; that we, to whom the Incarnation of Christ thy Son was made known by the message of an angel, may by his Passion and Cross be brought to the glory of his Resurrection. Through the same Christ our Lord. Amen.',
];

/** Stations of the Cross (traditional fourteen) */
export const STATIONS: Pair[] = [
  ['耶穌被判死刑', 'Jesus is condemned to death'],
  ['耶穌背負十字架', 'Jesus carries his cross'],
  ['耶穌第一次跌倒', 'Jesus falls the first time'],
  ['耶穌途遇聖母', 'Jesus meets his mother'],
  ['西滿幫耶穌背十字架', 'Simon of Cyrene helps Jesus carry the cross'],
  ['韋羅妮加為耶穌拭面', 'Veronica wipes the face of Jesus'],
  ['耶穌第二次跌倒', 'Jesus falls the second time'],
  ['耶穌勸慰耶路撒冷的婦女', 'Jesus meets the women of Jerusalem'],
  ['耶穌第三次跌倒', 'Jesus falls the third time'],
  ['耶穌被剝去衣服', 'Jesus is stripped of his garments'],
  ['耶穌被釘在十字架上', 'Jesus is nailed to the cross'],
  ['耶穌死在十字架上', 'Jesus dies on the cross'],
  ['耶穌的聖屍從十字架上卸下', 'Jesus is taken down from the cross'],
  ['耶穌被安葬在墳墓裡', 'Jesus is laid in the tomb'],
];
export const STATION_ACCLAMATION: Pair = [
  '基督，我們朝拜你，稱頌你，因為你藉著你的聖十字架救贖了普世。',
  'We adore you, O Christ, and we praise you, because by your holy cross you have redeemed the world.',
];

/** Fixed-date feasts of well-known saints and of Our Lady (month-day → name) */
export const FEASTS: Record<string, Pair> = {
  '01-01': ['天主之母節', 'Mary, Mother of God'],
  '01-25': ['聖保祿宗徒歸化', 'The Conversion of Saint Paul'],
  '01-28': ['聖多瑪斯・阿奎那', 'Saint Thomas Aquinas'],
  '02-02': ['獻耶穌於聖殿', 'The Presentation of the Lord'],
  '03-17': ['聖博德（聖派翠克）', 'Saint Patrick'],
  '03-19': ['大聖若瑟', 'Saint Joseph'],
  '03-25': ['預報救主降生', 'The Annunciation of the Lord'],
  '04-25': ['聖馬爾谷聖史', 'Saint Mark the Evangelist'],
  '04-29': ['瑟納聖加大利納', 'Saint Catherine of Siena'],
  '05-03': ['聖斐理伯及聖雅各伯宗徒', 'Saints Philip and James, Apostles'],
  '05-14': ['聖瑪弟亞宗徒', 'Saint Matthias the Apostle'],
  '05-31': ['聖母訪親', 'The Visitation of Mary'],
  '06-13': ['帕多瓦聖安多尼', 'Saint Anthony of Padua'],
  '06-24': ['洗者聖若翰誕辰', 'The Nativity of Saint John the Baptist'],
  '06-29': ['聖伯多祿及聖保祿宗徒', 'Saints Peter and Paul, Apostles'],
  '07-03': ['聖多默宗徒', 'Saint Thomas the Apostle'],
  '07-09': ['中華殉道聖人', 'Saint Augustine Zhao Rong and the Chinese Martyrs'],
  '07-11': ['聖本篤', 'Saint Benedict'],
  '07-22': ['聖瑪利亞瑪達肋納', 'Saint Mary Magdalene'],
  '07-25': ['聖雅各伯宗徒', 'Saint James the Apostle'],
  '07-26': ['聖若亞敬及聖亞納', 'Saints Joachim and Anne'],
  '07-31': ['聖依納爵・羅耀拉', 'Saint Ignatius of Loyola'],
  '08-08': ['聖道明', 'Saint Dominic'],
  '08-10': ['聖老楞佐', 'Saint Lawrence'],
  '08-11': ['聖佳蘭', 'Saint Clare'],
  '08-15': ['聖母蒙召升天', 'The Assumption of Mary'],
  '08-24': ['聖巴爾多祿茂宗徒', 'Saint Bartholomew the Apostle'],
  '08-27': ['聖莫尼加', 'Saint Monica'],
  '08-28': ['聖奧斯定', 'Saint Augustine'],
  '09-08': ['聖母誕辰', 'The Nativity of Mary'],
  '09-20': ['聖金大建神父及同伴殉道者', 'Saints Andrew Kim Tae-gon and Companions'],
  '09-21': ['聖瑪竇宗徒', 'Saint Matthew the Apostle'],
  '09-29': ['聖彌額爾、聖加俾額爾、聖辣法耳總領天使', 'Saints Michael, Gabriel and Raphael, Archangels'],
  '09-30': ['聖熱羅尼莫', 'Saint Jerome'],
  '10-01': ['聖女小德蘭', 'Saint Thérèse of Lisieux'],
  '10-02': ['護守天使', 'The Guardian Angels'],
  '10-04': ['亞西西聖方濟各', 'Saint Francis of Assisi'],
  '10-07': ['玫瑰聖母', 'Our Lady of the Rosary'],
  '10-15': ['聖女大德蘭', 'Saint Teresa of Ávila'],
  '10-18': ['聖路加聖史', 'Saint Luke the Evangelist'],
  '10-28': ['聖西滿及聖達陡宗徒', 'Saints Simon and Jude, Apostles'],
  '11-01': ['諸聖節', "All Saints' Day"],
  '11-02': ['追思已亡節', "All Souls' Day"],
  '11-30': ['聖安德肋宗徒', 'Saint Andrew the Apostle'],
  '12-03': ['聖方濟各・沙勿略', 'Saint Francis Xavier'],
  '12-08': ['聖母無原罪始胎', 'The Immaculate Conception'],
  '12-25': ['耶穌聖誕', 'The Nativity of the Lord (Christmas)'],
  '12-26': ['聖斯德望首位殉道者', 'Saint Stephen, the first martyr'],
  '12-27': ['聖若望宗徒', 'Saint John the Apostle'],
  '12-28': ['諸聖嬰孩殉道', 'The Holy Innocents'],
};

/** The 99 Names of God (transliteration, English meaning, Chinese meaning) */
export const NAMES_99: [string, string, string][] = [
  ['Ar-Rahman', 'The Most Merciful', '至仁的'],
  ['Ar-Rahim', 'The Most Compassionate', '至慈的'],
  ['Al-Malik', 'The King', '君主'],
  ['Al-Quddus', 'The Most Holy', '至聖的'],
  ['As-Salam', 'The Source of Peace', '平安的'],
  ["Al-Mu'min", 'The Giver of Security', '賜予安寧的'],
  ['Al-Muhaymin', 'The Guardian', '監護的'],
  ['Al-Aziz', 'The Almighty', '萬能的'],
  ['Al-Jabbar', 'The Compeller', '強大的'],
  ['Al-Mutakabbir', 'The Supreme in Greatness', '至尊的'],
  ['Al-Khaliq', 'The Creator', '創造者'],
  ["Al-Bari'", 'The Maker', '造化者'],
  ['Al-Musawwir', 'The Fashioner', '賦形者'],
  ['Al-Ghaffar', 'The Ever-Forgiving', '至赦的'],
  ['Al-Qahhar', 'The Subduer', '征服者'],
  ['Al-Wahhab', 'The Bestower', '施予者'],
  ['Ar-Razzaq', 'The Provider', '供給者'],
  ['Al-Fattah', 'The Opener', '開啟者'],
  ["Al-'Alim", 'The All-Knowing', '全知的'],
  ['Al-Qabid', 'The Withholder', '緊握者'],
  ['Al-Basit', 'The Extender', '寬舒者'],
  ['Al-Khafid', 'The Abaser', '降低者'],
  ["Ar-Rafi'", 'The Exalter', '升高者'],
  ["Al-Mu'izz", 'The Giver of Honour', '賜尊榮者'],
  ['Al-Mudhill', 'The Giver of Dishonour', '使卑賤者'],
  ["As-Sami'", 'The All-Hearing', '全聰的'],
  ['Al-Basir', 'The All-Seeing', '全明的'],
  ['Al-Hakam', 'The Judge', '裁判者'],
  ["Al-'Adl", 'The Just', '公正的'],
  ['Al-Latif', 'The Subtle, the Gentle', '精微的'],
  ['Al-Khabir', 'The All-Aware', '徹知的'],
  ['Al-Halim', 'The Forbearing', '寬容的'],
  ["Al-'Azim", 'The Magnificent', '偉大的'],
  ['Al-Ghafur', 'The All-Forgiving', '至恕的'],
  ['Ash-Shakur', 'The Appreciative', '厚報的'],
  ["Al-'Aliyy", 'The Most High', '至高的'],
  ['Al-Kabir', 'The Most Great', '至大的'],
  ['Al-Hafiz', 'The Preserver', '保護者'],
  ['Al-Muqit', 'The Sustainer', '養育者'],
  ['Al-Hasib', 'The Reckoner', '清算者'],
  ['Al-Jalil', 'The Majestic', '崇高的'],
  ['Al-Karim', 'The Generous', '慷慨的'],
  ['Ar-Raqib', 'The Watchful', '監察的'],
  ['Al-Mujib', 'The Responsive', '應答的'],
  ["Al-Wasi'", 'The All-Encompassing', '寬廣的'],
  ['Al-Hakim', 'The Wise', '睿智的'],
  ['Al-Wadud', 'The Loving', '慈愛的'],
  ['Al-Majid', 'The Most Glorious', '榮耀的'],
  ["Al-Ba'ith", 'The Resurrector', '復活者'],
  ['Ash-Shahid', 'The Witness', '見證者'],
  ['Al-Haqq', 'The Truth', '真實的'],
  ['Al-Wakil', 'The Trustee', '受託者'],
  ['Al-Qawiyy', 'The Strong', '強壯的'],
  ['Al-Matin', 'The Firm', '堅定的'],
  ['Al-Waliyy', 'The Protecting Friend', '護佑者'],
  ['Al-Hamid', 'The Praiseworthy', '可頌的'],
  ['Al-Muhsi', 'The Accounter', '統計者'],
  ["Al-Mubdi'", 'The Originator', '首創者'],
  ["Al-Mu'id", 'The Restorer', '復生者'],
  ['Al-Muhyi', 'The Giver of Life', '賜生者'],
  ['Al-Mumit', 'The Bringer of Death', '使死者'],
  ['Al-Hayy', 'The Ever-Living', '永生的'],
  ['Al-Qayyum', 'The Self-Subsisting', '自存的'],
  ['Al-Wajid', 'The Perceiver', '無所缺的'],
  ['Al-Majid', 'The Noble', '尊貴的'],
  ['Al-Wahid', 'The One', '獨一的'],
  ['Al-Ahad', 'The Unique', '唯一的'],
  ['As-Samad', 'The Eternal Refuge', '永恆的'],
  ['Al-Qadir', 'The Able', '全能的'],
  ['Al-Muqtadir', 'The Powerful', '大能的'],
  ['Al-Muqaddim', 'The Expediter', '提前者'],
  ["Al-Mu'akhkhir", 'The Delayer', '延後者'],
  ['Al-Awwal', 'The First', '首先的'],
  ['Al-Akhir', 'The Last', '最後的'],
  ['Az-Zahir', 'The Manifest', '顯著的'],
  ['Al-Batin', 'The Hidden', '隱微的'],
  ['Al-Wali', 'The Governor', '主宰者'],
  ["Al-Muta'ali", 'The Most Exalted', '超絕的'],
  ['Al-Barr', 'The Source of Goodness', '至善的'],
  ['At-Tawwab', 'The Accepter of Repentance', '接受懺悔的'],
  ['Al-Muntaqim', 'The Avenger', '懲罰者'],
  ["Al-'Afuww", 'The Pardoner', '恕饒的'],
  ["Ar-Ra'uf", 'The Most Kind', '仁愛的'],
  ['Malik al-Mulk', 'Owner of All Sovereignty', '國權的主'],
  ['Dhul-Jalali wal-Ikram', 'Lord of Majesty and Generosity', '具有尊嚴與慷慨的'],
  ['Al-Muqsit', 'The Equitable', '公平的'],
  ["Al-Jami'", 'The Gatherer', '集合者'],
  ['Al-Ghaniyy', 'The Self-Sufficient', '富足的'],
  ['Al-Mughni', 'The Enricher', '使富足者'],
  ["Al-Mani'", 'The Preventer', '阻止者'],
  ['Ad-Darr', 'The Distresser', '降害者'],
  ["An-Nafi'", 'The Benefactor', '施益者'],
  ['An-Nur', 'The Light', '光明的'],
  ['Al-Hadi', 'The Guide', '引導者'],
  ["Al-Badi'", 'The Incomparable Originator', '創新者'],
  ['Al-Baqi', 'The Everlasting', '永存的'],
  ['Al-Warith', 'The Inheritor', '繼承者'],
  ['Ar-Rashid', 'The Guide to the Right Path', '正道的'],
  ['As-Sabur', 'The Patient', '堅忍的'],
];

/** Gayatri mantra (Rigveda 3.62.10) */
export const GAYATRI = {
  devanagari: 'ॐ भूर्भुवः स्वः\nतत्सवितुर्वरेण्यं\nभर्गो देवस्य धीमहि\nधियो यो नः प्रचोदयात्',
  roman: 'Oṃ bhūr bhuvaḥ svaḥ\ntat savitur vareṇyaṃ\nbhargo devasya dhīmahi\ndhiyo yo naḥ pracodayāt',
  meaning: [
    '我們冥想太陽神薩維特里（Savitr）那值得敬拜的神聖光輝，願祂啟發我們的心智。',
    'We meditate on the adorable glory of the divine Savitr (the Sun); may it inspire our minds.',
  ] as Pair,
};
